// This file is auto-generated by scripts/generate.js

import * as z from "zod/v4";

import type * as types from "./types.gen.js";
import * as validate from "./zod.gen.js";

function tagOf(value: unknown, key: string): unknown {
  return typeof value === "object" && value !== null
    ? (value as Record<string, unknown>)[key]
    : undefined;
}

const zGuardCreateElicitationRequestForm = validate.zElicitationFormMode
  .and(z.object({ mode: z.literal("form") }))
  .and(z.object({ message: z.string() }));
const zGuardCreateElicitationRequestUrl = validate.zElicitationUrlMode
  .and(z.object({ mode: z.literal("url") }))
  .and(z.object({ message: z.string() }));
const zGuardCreateElicitationRequestCustom = z
  .union([validate.zElicitationSessionScope, validate.zElicitationRequestScope])
  .and(z.object({ message: z.string() }));
const zGuardElicitationPropertySchemaString =
  validate.zStringPropertySchema.and(z.object({ type: z.literal("string") }));
const zGuardElicitationPropertySchemaNumber =
  validate.zNumberPropertySchema.and(z.object({ type: z.literal("number") }));
const zGuardElicitationPropertySchemaInteger =
  validate.zIntegerPropertySchema.and(z.object({ type: z.literal("integer") }));
const zGuardElicitationPropertySchemaBoolean =
  validate.zBooleanPropertySchema.and(z.object({ type: z.literal("boolean") }));
const zGuardElicitationPropertySchemaArray =
  validate.zMultiSelectPropertySchema.and(
    z.object({ type: z.literal("array") }),
  );
const zGuardMultiSelectItemsString = validate.zStringMultiSelectItems.and(
  z.object({ type: z.literal("string") }),
);
const zGuardMultiSelectItemsTitled = validate.zTitledMultiSelectItems;
const zGuardCreateElicitationResponseAccept =
  validate.zElicitationAcceptAction.and(
    z.object({ action: z.literal("accept") }),
  );
const zGuardCreateElicitationResponseDecline = z.object({
  action: z.literal("decline"),
});
const zGuardCreateElicitationResponseCancel = z.object({
  action: z.literal("cancel"),
});

/**
 * **UNSTABLE**
 *
 * This capability is not part of the spec yet, and may be removed or changed at any point.
 *
 * Request from the agent to elicit structured user input.
 *
 * The agent sends this to the client to request information from the user,
 * either via a form or by directing them to a URL.
 * Elicitations are tied to a session (optionally a tool call) or a request.
 *
 * @experimental
 */
export type CreateElicitationRequest = types.CreateElicitationRequest;
/**
 * Validated type guards for `CreateElicitationRequest`'s known variants.
 *
 * Each guard validates the variant's payload, not just its discriminant
 * tag: a malformed known variant (right tag, wrong payload) matches no
 * guard — mirroring wire validation, which rejects such values instead
 * of classifying them as custom.
 *
 * Guards check the value as given: fields that wire deserialization
 * salvages to a default (e.g. a malformed `_meta`) are only normalized
 * by parsing, and for ambiguous raw shapes (a known tag combined with
 * another variant's payload) guards are conservative where wire parsing
 * may still accept the value — narrow wire-parsed values when exact
 * parity matters.
 *
 * @experimental
 */
export const CreateElicitationRequest = {
  /** Narrow to the `form` variant, validating its payload. */
  isForm(
    value: types.CreateElicitationRequest,
  ): value is (types.ElicitationFormMode & { mode: "form" }) &
    Pick<types.CreateElicitationRequest, "message" | "_meta"> {
    return (
      tagOf(value, "mode") === "form" &&
      zGuardCreateElicitationRequestForm.safeParse(value).success
    );
  },

  /** Narrow to the `url` variant, validating its payload. */
  isUrl(
    value: types.CreateElicitationRequest,
  ): value is (types.ElicitationUrlMode & { mode: "url" }) &
    Pick<types.CreateElicitationRequest, "message" | "_meta"> {
    return (
      tagOf(value, "mode") === "url" &&
      zGuardCreateElicitationRequestUrl.safeParse(value).success
    );
  },

  /**
   * Narrow to a custom or future variant: the `mode` tag matches no known variant, with a valid payload.
   *
   * TypeScript keeps the known variants in the narrowed union (they are
   * structural subtypes of the catch-all), so read vendor payload keys
   * via a widening cast: `(value as Record<string, unknown>).someKey`.
   */
  isCustom(
    value: types.CreateElicitationRequest,
  ): value is ((
    types.ElicitationSessionScope | types.ElicitationRequestScope
  ) & { mode: string; [key: string]: unknown }) &
    Pick<types.CreateElicitationRequest, "message" | "_meta"> {
    const tag = tagOf(value, "mode");
    return (
      typeof tag === "string" &&
      !["form", "url"].includes(tag) &&
      zGuardCreateElicitationRequestCustom.safeParse(value).success
    );
  },
} as const;

/**
 * Property schema for elicitation form fields.
 *
 * Each variant corresponds to a JSON Schema `"type"` value.
 * Single-select enums use the `String` variant with `enum` or `oneOf` set.
 * Multi-select enums use the `Array` variant.
 */
export type ElicitationPropertySchema = types.ElicitationPropertySchema;
/**
 * Validated type guards for `ElicitationPropertySchema`'s known variants.
 *
 * Each guard validates the variant's payload, not just its discriminant
 * tag: a malformed known variant (right tag, wrong payload) matches no
 * guard — mirroring wire validation, which rejects such values instead
 * of classifying them as custom.
 *
 * Guards check the value as given: fields that wire deserialization
 * salvages to a default (e.g. a malformed `_meta`) are only normalized
 * by parsing, and for ambiguous raw shapes (a known tag combined with
 * another variant's payload) guards are conservative where wire parsing
 * may still accept the value — narrow wire-parsed values when exact
 * parity matters.
 */
export const ElicitationPropertySchema = {
  /** Narrow to the `string` variant, validating its payload. */
  isString(
    value: types.ElicitationPropertySchema,
  ): value is types.StringPropertySchema & { type: "string" } {
    return (
      tagOf(value, "type") === "string" &&
      zGuardElicitationPropertySchemaString.safeParse(value).success
    );
  },

  /** Narrow to the `number` variant, validating its payload. */
  isNumber(
    value: types.ElicitationPropertySchema,
  ): value is types.NumberPropertySchema & { type: "number" } {
    return (
      tagOf(value, "type") === "number" &&
      zGuardElicitationPropertySchemaNumber.safeParse(value).success
    );
  },

  /** Narrow to the `integer` variant, validating its payload. */
  isInteger(
    value: types.ElicitationPropertySchema,
  ): value is types.IntegerPropertySchema & { type: "integer" } {
    return (
      tagOf(value, "type") === "integer" &&
      zGuardElicitationPropertySchemaInteger.safeParse(value).success
    );
  },

  /** Narrow to the `boolean` variant, validating its payload. */
  isBoolean(
    value: types.ElicitationPropertySchema,
  ): value is types.BooleanPropertySchema & { type: "boolean" } {
    return (
      tagOf(value, "type") === "boolean" &&
      zGuardElicitationPropertySchemaBoolean.safeParse(value).success
    );
  },

  /** Narrow to the `array` variant, validating its payload. */
  isArray(
    value: types.ElicitationPropertySchema,
  ): value is types.MultiSelectPropertySchema & { type: "array" } {
    return (
      tagOf(value, "type") === "array" &&
      zGuardElicitationPropertySchemaArray.safeParse(value).success
    );
  },

  /**
   * Narrow to a custom or future variant: the `type` tag matches no known variant.
   *
   * TypeScript keeps the known variants in the narrowed union (they are
   * structural subtypes of the catch-all), so read vendor payload keys
   * via a widening cast: `(value as Record<string, unknown>).someKey`.
   */
  isCustom(
    value: types.ElicitationPropertySchema,
  ): value is { type: string; [key: string]: unknown } {
    const tag = tagOf(value, "type");
    return (
      typeof tag === "string" &&
      !["array", "boolean", "integer", "number", "string"].includes(tag)
    );
  },
} as const;

/**
 * Items for a multi-select (array) property schema.
 */
export type MultiSelectItems = types.MultiSelectItems;
/**
 * Validated type guards for `MultiSelectItems`'s known variants.
 *
 * Each guard validates the variant's payload, not just its discriminant
 * tag: a malformed known variant (right tag, wrong payload) matches no
 * guard — mirroring wire validation, which rejects such values instead
 * of classifying them as custom.
 *
 * Guards check the value as given: fields that wire deserialization
 * salvages to a default (e.g. a malformed `_meta`) are only normalized
 * by parsing, and for ambiguous raw shapes (a known tag combined with
 * another variant's payload) guards are conservative where wire parsing
 * may still accept the value — narrow wire-parsed values when exact
 * parity matters.
 */
export const MultiSelectItems = {
  /** Narrow to the `string` variant, validating its payload. */
  isString(
    value: types.MultiSelectItems,
  ): value is types.StringMultiSelectItems & { type: "string" } {
    return (
      tagOf(value, "type") === "string" &&
      zGuardMultiSelectItemsString.safeParse(value).success
    );
  },

  /** Narrow to the `titled` variant, validating its payload. */
  isTitled(
    value: types.MultiSelectItems,
  ): value is types.TitledMultiSelectItems {
    return (
      tagOf(value, "type") === undefined &&
      zGuardMultiSelectItemsTitled.safeParse(value).success
    );
  },

  /**
   * Narrow to a custom or future variant: the `type` tag matches no known variant.
   *
   * TypeScript keeps the known variants in the narrowed union (they are
   * structural subtypes of the catch-all), so read vendor payload keys
   * via a widening cast: `(value as Record<string, unknown>).someKey`.
   */
  isCustom(
    value: types.MultiSelectItems,
  ): value is { type: string; [key: string]: unknown } {
    const tag = tagOf(value, "type");
    return typeof tag === "string" && !["string"].includes(tag);
  },
} as const;

/**
 * **UNSTABLE**
 *
 * This capability is not part of the spec yet, and may be removed or changed at any point.
 *
 * Response from the client to an elicitation request.
 *
 * @experimental
 */
export type CreateElicitationResponse = types.CreateElicitationResponse;
/**
 * Validated type guards for `CreateElicitationResponse`'s known variants.
 *
 * Each guard validates the variant's payload, not just its discriminant
 * tag: a malformed known variant (right tag, wrong payload) matches no
 * guard — mirroring wire validation, which rejects such values instead
 * of classifying them as custom.
 *
 * Guards check the value as given: fields that wire deserialization
 * salvages to a default (e.g. a malformed `_meta`) are only normalized
 * by parsing, and for ambiguous raw shapes (a known tag combined with
 * another variant's payload) guards are conservative where wire parsing
 * may still accept the value — narrow wire-parsed values when exact
 * parity matters.
 *
 * @experimental
 */
export const CreateElicitationResponse = {
  /** Narrow to the `accept` variant, validating its payload. */
  isAccept(
    value: types.CreateElicitationResponse,
  ): value is (types.ElicitationAcceptAction & { action: "accept" }) &
    Pick<types.CreateElicitationResponse, "_meta"> {
    return (
      tagOf(value, "action") === "accept" &&
      zGuardCreateElicitationResponseAccept.safeParse(value).success
    );
  },

  /** Narrow to the `decline` variant, validating its payload. */
  isDecline(
    value: types.CreateElicitationResponse,
  ): value is { action: "decline" } & Pick<
    types.CreateElicitationResponse,
    "_meta"
  > {
    return (
      tagOf(value, "action") === "decline" &&
      zGuardCreateElicitationResponseDecline.safeParse(value).success
    );
  },

  /** Narrow to the `cancel` variant, validating its payload. */
  isCancel(
    value: types.CreateElicitationResponse,
  ): value is { action: "cancel" } & Pick<
    types.CreateElicitationResponse,
    "_meta"
  > {
    return (
      tagOf(value, "action") === "cancel" &&
      zGuardCreateElicitationResponseCancel.safeParse(value).success
    );
  },

  /**
   * Narrow to a custom or future variant: the `action` tag matches no known variant.
   *
   * TypeScript keeps the known variants in the narrowed union (they are
   * structural subtypes of the catch-all), so read vendor payload keys
   * via a widening cast: `(value as Record<string, unknown>).someKey`.
   */
  isCustom(
    value: types.CreateElicitationResponse,
  ): value is { action: string; [key: string]: unknown } & Pick<
    types.CreateElicitationResponse,
    "_meta"
  > {
    const tag = tagOf(value, "action");
    return (
      typeof tag === "string" && !["accept", "cancel", "decline"].includes(tag)
    );
  },
} as const;
